server:
  port: 8801

spring:
  application:
    name: employee-managment-service

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    root: INFO
    org.springframework.boot: WARN
    org.springframework.web: WARN
    com.netflix: WARN



